export const ROUTES = {
  AUTH: {
    LOGIN: '/login',
    LOGOUT: '/logout',
    MFA_SETUP: '/mfa/setup',
    MFA_VERIFY: '/mfa/verify',
    PASSWORD_RESET: '/password-reset',
  },
  PLATFORM: {
    ROOT: '/platform',
    DASHBOARD: '/platform/dashboard',
    TENANTS: '/platform/tenants',
    TENANTS_NEW: '/platform/tenants/new',
    TENANT_DETAIL: (tenantId: string) => `/platform/tenants/${tenantId}`,
    PLANS: '/platform/plans',
    USAGE: '/platform/usage',
    SUPPORT: '/platform/support',
    AUDIT: '/platform/audit',
    CONFIG: '/platform/config',
  },
  TENANT: {
    DASHBOARD: '/dashboard',
    ORGANISATION: {
      ROOT:                '/organisation',
      LEGAL_ENTITIES:      '/organisation/legal-entities',
      LEGAL_ENTITY_NEW:    '/organisation/legal-entities/new',
      LEGAL_ENTITY_DETAIL: (id: string) => `/organisation/legal-entities/${id}`,
      BRANCHES:            '/organisation/branches',
      BRANCH_NEW:          '/organisation/branches/new',
      BRANCH_DETAIL:       (id: string) => `/organisation/branches/${id}`,
      DEPARTMENTS:         '/organisation/departments',
      DEPARTMENT_NEW:      '/organisation/departments/new',
      DEPARTMENT_DETAIL:   (id: string) => `/organisation/departments/${id}`,
      COST_CENTRES:        '/organisation/cost-centres',
      COST_CENTRE_NEW:     '/organisation/cost-centres/new',
      COST_CENTRE_DETAIL:  (id: string) => `/organisation/cost-centres/${id}`,
      POSITIONS:           '/organisation/positions',
      POSITION_NEW:        '/organisation/positions/new',
      POSITION_DETAIL:     (id: string) => `/organisation/positions/${id}`,
    },
    EMPLOYEES: {
      ROOT:   '/employees',
      NEW:    '/employees/new',
      DETAIL: (id: string) => `/employees/${id}`,
      EDIT:   (id: string) => `/employees/${id}/edit`,
    },
    DOCUMENTS: {
      ROOT:               '/documents',
      TEMPLATES:          '/documents/templates',
      TEMPLATE_NEW:       '/documents/templates/new',
      TEMPLATE_DETAIL:    (id: string) => `/documents/templates/${id}`,
      ONBOARDING:         '/documents/onboarding',
      ONBOARDING_NEW:     '/documents/onboarding/new',
      ONBOARDING_DETAIL:  (id: string) => `/documents/onboarding/${id}`,
    },
    ATTENDANCE: {
      ROOT:          '/attendance',
      RECORDS:       '/attendance/records',
      RECORD_DETAIL: (id: string) => `/attendance/records/${id}`,
      POLICIES:      '/attendance/policies',
      POLICY_NEW:    '/attendance/policies/new',
      POLICY_DETAIL: (id: string) => `/attendance/policies/${id}`,
    },
    LEAVE: '/leave',
    SHIFTS: '/shifts',
    PAYROLL: '/payroll',
    REPORTS: '/reports',
    SETTINGS: '/settings',
  },
  EMPLOYEE: {
    DASHBOARD: '/my',
    ATTENDANCE: '/my/attendance',
    LEAVE: '/my/leave',
    PAYSLIPS: '/my/payslips',
    PROFILE: '/my/profile',
  },
} as const;
